Use docker hub to distribute yppf image (#560)

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
 
-  build:
+  build-and-test:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
@@ -30,11 +30,14 @@ jobs:
     
     - name: Check host
       run: |
-          timeout 60s bash -c "while ! curl -Is localhost:8000; do
-                                 sleep 2
-                               done" ||
-          "docker-compose -f env/docker-compose.yml logs && exit 1"
+        docker ps -a
+        sleep 10
+        timeout 30s bash -c "while ! curl -Is localhost:8000; do
+                                sleep 3
+                                echo 'Failed to fetch web page.'
+                              done" ||
+        "docker-compose -f env/docker-compose.yml logs && exit 1"
 
     - name: Test 
       run: |
-        docker-compose -f env/docker-compose.yml run yppf python3 manage.py test
+        docker-compose -f env/docker-compose.yml run yppf conda run -n yppf python3 manage.py test
